"use client"
import { useEffect, useRef, useState } from "react"
import { useQueryClient } from "@tanstack/react-query"
import { toast } from "sonner"
import { apiClient } from "@/lib/api"
import s from "./account.module.css"
type User={id:string;email:string;name:string;theme:"dark"|"light"|"system";density:"comfortable"|"default"|"compact";timezone:string}
type Session={id:string;device:string;last_seen:number;expires_at:number;current:boolean}
type Key={id:string;name:string;prefix:string;created_at:number;expires_at:number;last_seen:number|null}
const time=(value:number)=>new Date(value*1000).toISOString().replace("T"," ").slice(0,19)+"Z"
export default function AccountPage(){
 const queryClient=useQueryClient()
 const clearPrivateState=()=>{queryClient.clear();window.dispatchEvent(new Event("olus-account-changed"))}
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("")
 const [sessions,setSessions]=useState<Session[]>([]),[keys,setKeys]=useState<Key[]>([]),[issued,setIssued]=useState("")
 const [confirmation,setConfirmation]=useState<{label:string;action:()=>Promise<void>}|null>(null),dialog=useRef<HTMLDialogElement>(null),confirmTrigger=useRef<HTMLElement|null>(null)
 const refreshLists=async()=>{const [a,b]=await Promise.all([apiClient.get<Session[]>("/account/sessions"),apiClient.get<Key[]>("/account/keys")]);setSessions(a.data);setKeys(b.data)}
 useEffect(()=>{let active=true;apiClient.get<{user:User}>("/account/session").then(async r=>{if(active){setUser(r.data.user);await refreshLists()}}).catch(e=>{if(active && !String(e.message).includes("Sign in required"))setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError("");try{await action()}catch(e){setError(e instanceof Error?e.message:"Request failed");toast.error("Unable to save",{description:e instanceof Error?e.message:"Retry the action."})}finally{setBusy(false)}}
 const confirm=(label:string,action:()=>Promise<void>)=>{setError("");confirmTrigger.current=document.activeElement as HTMLElement;setConfirmation({label,action});dialog.current?.showModal()}
 const closeConfirm=()=>{dialog.current?.close();setConfirmation(null);setError("");confirmTrigger.current?.focus()}
 const saveProfile=(next:User)=>run(async()=>{await apiClient.patch("/account/profile",next);setUser(next);localStorage.setItem("olus-workspace-theme",next.theme);localStorage.setItem("olus-workspace-density",next.density);window.dispatchEvent(new CustomEvent("olus-preferences-changed",{detail:{theme:next.theme,density:next.density}}));toast.success("Preferences saved")})
 if(loading)return <div className={s.page} role="status">Loading your account...</div>
 return <div className={s.page}><header><p>WORKSPACE / ACCOUNT</p><h1>{user?"Your account":"Sign in"}</h1><p>{user?"Profile, preferences and access to your private workspace.":"Use the account provisioned by your workspace operator. The public simulator remains available without signing in."}</p></header>
 {error&&!confirmation&&<p role="alert" className={s.error}>{error}</p>}
 {!user?<form className={s.form} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void run(async()=>{const r=await apiClient.post<{user:User}>("/account/login",{email:data.get("email"),password:data.get("password")});clearPrivateState();setUser(r.data.user);await refreshLists();toast.success("Signed in")})}}><label>Email<input type="email" name="email" autoComplete="username" required maxLength={254}/></label><label>Password<input type="password" name="password" autoComplete="current-password" required maxLength={128}/></label><button className={s.primary} disabled={busy} aria-busy={busy}>{busy?"Signing in...":"Sign in"}</button><p>New accounts are provisioned on the API host. Ask your operator for access; this page does not create a shared or anonymous account.</p></form>:<>
 <section><div className={s.heading}><h2>Profile</h2><button disabled={busy} onClick={()=>void run(async()=>{await apiClient.post("/account/logout");clearPrivateState();setUser(null);setIssued("");toast.success("Signed out")})}>Sign out</button></div><label>Display name<input value={user.name} maxLength={100} onChange={e=>setUser({...user,name:e.target.value})} onBlur={()=>void saveProfile(user)}/></label><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);void run(async()=>{const r=await apiClient.patch<{email:string}>("/account/email",{email:data.get("email"),password:data.get("password")});setUser({...user,email:r.data.email});form.reset();toast.success("Email saved")})}}><label>Email<input key={user.email} type="email" name="email" defaultValue={user.email} required maxLength={254}/></label><label>Current password to change email<input type="password" name="password" autoComplete="current-password" required maxLength={128}/></label><button disabled={busy}>Save email</button></form></section>
 <section><h2>Preferences</h2><div className={s.preferences}><label>Theme<select value={user.theme} disabled={busy} onChange={e=>void saveProfile({...user,theme:e.target.value as User["theme"]})}><option value="system">System</option><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Density<select value={user.density} disabled={busy} onChange={e=>void saveProfile({...user,density:e.target.value as User["density"]})}><option value="comfortable">Comfortable</option><option value="default">Default</option><option value="compact">Compact</option></select></label><label>Preferred timezone<input defaultValue={user.timezone} placeholder="UTC" onBlur={e=>{if(e.target.value!==user.timezone)void saveProfile({...user,timezone:e.target.value})}}/></label></div><p>Operational timestamps stay in UTC with a Z suffix. Your timezone preference is stored for account displays that support localization.</p></section>
 <section><h2>API keys</h2><p>Keys expire after 90 days. They authorize your private account APIs, including saved workspaces. Existing key secrets cannot be revealed again.</p>{issued&&<div className={s.secret} role="status"><strong>Copy this key now. It is shown once.</strong><code>{issued}</code><button onClick={()=>void navigator.clipboard.writeText(issued).then(()=>toast.success("Key copied")).catch(()=>toast.error("Copy unavailable; select the key to copy it."))}>Copy key</button><button onClick={()=>setIssued("")}>I saved the key</button></div>}<form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);void run(async()=>{const r=await apiClient.post<{key:string}>("/account/keys",{name:data.get("name")});setIssued(r.data.key);form.reset();await refreshLists()})}}><label>Key name<input name="name" required maxLength={80} placeholder="Operations integration"/></label><button className={s.primary} disabled={busy}>Create key</button></form>{keys.length===0?<p>No API keys. Create one only when connecting an integration.</p>:<ul className={s.list}>{keys.map(key=><li key={key.id}><div><strong>{key.name}</strong><p><code>{key.prefix}...</code> · Expires {time(key.expires_at)}</p><small>Last used: {key.last_seen?time(key.last_seen):"Never"}</small></div><button disabled={busy} onClick={()=>confirm(`Rotate ${key.name}? The old key will stop working immediately.`,async()=>{const r=await apiClient.post<{key:string}>(`/account/keys/${key.id}/rotate`);setIssued(r.data.key);await refreshLists();toast.success("Key rotated")})}>Rotate</button><button className={s.destructive} disabled={busy} onClick={()=>confirm(`Revoke ${key.name}? Connected integrations will lose access.`,async()=>{await apiClient.del(`/account/keys/${key.id}`);await refreshLists();toast.success("Key revoked")})}>Revoke</button></li>)}</ul>}</section>
 <section><h2>Active sessions</h2><ul className={s.list}>{sessions.map(session=><li key={session.id}><div><strong>{session.current?"This session":"Other session"}</strong><p className={s.device}>{session.device}</p><small>Last seen {time(session.last_seen)}</small></div><button className={s.destructive} disabled={busy} onClick={()=>confirm("Revoke this session? It will need to sign in again.",async()=>{await apiClient.del(`/account/sessions/${session.id}`);if(session.current){clearPrivateState();setUser(null);setIssued("")}else await refreshLists();toast.success("Session revoked")})}>Revoke session</button></li>)}</ul></section>
 <section><h2>Change password</h2><p>Changing your password revokes other sessions and all API keys.</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);confirm("Change your password and revoke other sessions and keys?",async()=>{await apiClient.patch("/account/password",{current_password:data.get("current"),new_password:data.get("next")});form.reset();setIssued("");await refreshLists();toast.success("Password changed")})}}><label>Current password<input name="current" type="password" autoComplete="current-password" required maxLength={128}/></label><label>New password<input name="next" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><button disabled={busy}>Change password</button></form></section>
 <section className={s.danger}><h2>Delete account</h2><p>Deletes your sign-in, preferences, sessions and API keys. Saved simulation records are retained by the workspace operator; account deletion does not erase shared operational records.</p><form onSubmit={e=>{e.preventDefault();const password=new FormData(e.currentTarget).get("password");confirm("Permanently delete your account? This cannot be undone.",async()=>{await apiClient.post("/account/delete",{password});clearPrivateState();setUser(null);setIssued("");toast.success("Account deleted")})}}><label>Current password<input name="password" type="password" autoComplete="current-password" required maxLength={128}/></label><button className={s.destructive} disabled={busy}>Delete account</button></form></section>
 </>}
 <dialog ref={dialog} className={s.dialog} aria-labelledby="account-confirm" onCancel={e=>{e.preventDefault();if(!busy)closeConfirm()}}><h2 id="account-confirm">{confirmation?.label}</h2>{error&&<p role="alert" className={s.error}>{error}</p>}<div><button autoFocus disabled={busy} onClick={closeConfirm}>Cancel</button><button className={s.destructive} disabled={busy} aria-busy={busy} onClick={()=>void run(async()=>{await confirmation?.action();closeConfirm()})}>{busy?"Saving...":"Confirm"}</button></div></dialog>
 </div>
}
