"use client"
import Image from "next/image"
import Link from "next/link"
import type { Route } from "next"
import { useLayoutEffect, useRef } from "react"
import { facts } from "@/lib/facts"
import { media } from "@/lib/media"
import { gsap } from "./gsap"
import { NetworkGlobe } from "./network-globe"
import { RecoveryFooter } from "./recovery-footer"
import s from "./recovery-story.module.css"

const pictures=[{image:media.stand,caption:"01 / THE AIRCRAFT"},{image:media.approach,caption:"02 / THE NETWORK"},{image:media.night,caption:"03 / THE TURNAROUND"},{image:media.cabin,caption:"04 / THE PASSENGER"},{image:media.hero,caption:"05 / THE RECOVERY"}]
const constraints=[
 ["DUTY CLOCKS, IN CONTEXT","Follow flight time, duty periods, and rest windows alongside the affected aircraft rotation. A recovered schedule must work for the crew flying it."],
 ["A RULE BEHIND EACH DECISION","Inspect the implemented Part 117 checks and their inputs. Feasible and optimal are distinct solver outcomes, and the interface keeps that distinction visible."],
 ["REPLAY THE SAME DISRUPTION","Saved events, frozen weather snapshots, and a single-worker seeded solver make recovery decisions traceable in deterministic replay mode."],
 ["RECOVER THE WHOLE ROTATION","Weather, airspace restrictions, aircraft failures, and crew availability propagate through the schedule. Compare the consequences before choosing a plan."]]

function Gallery(){
 const ref=useRef<HTMLElement>(null)
 useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add("(min-width:768px) and (prefers-reduced-motion:no-preference)",()=>{
  const root=ref.current!,pin=root.querySelector<HTMLElement>("[data-gallery-pin]")!,track=root.querySelector<HTMLElement>("[data-gallery-track]")!,cards=Array.from(root.querySelectorAll<HTMLElement>("[data-gallery-card]")),state={p:0}
  const paint=()=>{const stride=innerWidth*.38;gsap.set(track,{x:-state.p*stride*(cards.length-1)});cards.forEach((card,i)=>{const d=Math.min(1,Math.abs(i-state.p*(cards.length-1)));gsap.set(card,{scale:1-d*.64,y:d*-120,opacity:1-d*.25})})};paint()
  gsap.to(state,{p:1,ease:"none",onUpdate:paint,scrollTrigger:{id:"olus-gallery",trigger:root,start:"top top",end:"+=400%",pin,scrub:1,invalidateOnRefresh:true}})
  gsap.fromTo(root.querySelector("[data-progress]"),{scaleX:0},{scaleX:1,ease:"none",scrollTrigger:{trigger:root,start:"top top",end:"+=400%",scrub:1}})
 },ref);return()=>mm.revert()},[])
 return <section ref={ref} id="highlights" className={s.gallery} aria-labelledby="gallery-title"><div className={s.galleryPin} data-gallery-pin><h2 id="gallery-title" className={s.galleryTitle}>Chaos, solved.</h2><div className={s.galleryTrack} data-gallery-track>{pictures.map(({image,caption})=><figure key={caption} className={s.galleryCard} data-gallery-card><div className={s.galleryImage}><Image {...image} alt={image.alt} fill sizes="(max-width:767px) 90vw, 40vw" placeholder="blur" /></div><figcaption><span>{caption}</span><span aria-hidden>↗</span></figcaption></figure>)}</div><div className={s.galleryFoot}><span>SIMULATION HIGHLIGHTS</span><Link href="/scenarios">Run the storm ↗</Link></div><div className={s.progress}><i data-progress /></div></div></section>
}
function RecoveryJourney(){
 const ref=useRef<HTMLElement>(null)
 useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add("(prefers-reduced-motion:no-preference)",()=>{const root=ref.current!,path=root.querySelector<SVGPathElement>("[data-route]")!,plane=root.querySelector("[data-route-plane]")!,length=path.getTotalLength(),state={p:0};gsap.set(path,{strokeDasharray:length,strokeDashoffset:length});gsap.to(state,{p:1,ease:"none",onUpdate:()=>{const point=path.getPointAtLength(state.p*length),next=path.getPointAtLength(Math.min(length,state.p*length+1));gsap.set(path,{strokeDashoffset:(1-state.p)*length});gsap.set(plane,{x:point.x,y:point.y,rotation:Math.atan2(next.y-point.y,next.x-point.x)*180/Math.PI})},scrollTrigger:{trigger:root,start:"top 65%",end:"center 35%",scrub:.7}});gsap.from(root.querySelectorAll("[data-reveal]"),{y:40,opacity:0,stagger:.12,duration:.8,ease:"power3.out",scrollTrigger:{trigger:root,start:"top 80%"}})},ref);return()=>mm.revert()},[])
 return <section ref={ref} id="journey" className={s.section} aria-labelledby="journey-title"><div className={s.journeyGrid}><div className={s.journeyMain} data-reveal><Image {...media.hero} alt={media.hero.alt} fill sizes="(max-width:767px) 100vw, 72vw" placeholder="blur" /><div className={s.journeyCard}><span className={s.eyebrow}>RECOVERY PLAN</span><h3>IRROPS–2291 / 07:42Z</h3><small>Illustrative workflow</small><svg viewBox="0 0 320 220" aria-label="A route from disruption to reviewed recovery"><path d="M20 185 Q70 25 180 45 T300 60" fill="none" stroke="var(--control-border)" strokeWidth="1"/><path data-route d="M20 185 Q70 25 180 45 T300 60" fill="none" stroke="var(--recover)" strokeWidth="2"/><circle cx="20" cy="185" r="7" fill="var(--disrupt)"/><circle cx="300" cy="60" r="7" fill="var(--recover)"/><g data-route-plane transform="translate(300 60)"><path d="M11 0L-7 -8L-3 0L-7 8Z" fill="var(--text-hi)"/></g><text x="8" y="214" fill="var(--text-hi)" fontSize="11">DISRUPTED</text><text x="226" y="91" fill="var(--text-hi)" fontSize="11">REVIEWED</text></svg><div className={s.journeyTimes}><span>01<br/>Detect</span><span>02<br/>Solve</span><span>03<br/>Review</span></div></div></div><figure className={s.journeySide} data-reveal><div><Image {...media.cabin} alt={media.cabin.alt} fill sizes="(max-width:767px) 35vw, 24vw" placeholder="blur"/></div><figcaption>Re-time the flight. Reassign the aircraft. Check the crew. See the effect on everyone waiting downline.</figcaption></figure></div><div className={s.journeyHeading}><span className={s.eyebrow}>FROM ALERT TO A DECISION</span><h2 id="journey-title">The next move,<br/>with the whole picture.</h2></div></section>
}
function Technology(){const ref=useRef<HTMLElement>(null);useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add("(prefers-reduced-motion:no-preference)",()=>{gsap.fromTo(ref.current!.querySelector("[data-tech-image]"),{yPercent:8},{yPercent:-8,ease:"none",scrollTrigger:{trigger:ref.current,start:"top bottom",end:"bottom top",scrub:true}})},ref);return()=>mm.revert()},[]);return <section ref={ref} id="technology" className={s.tech}><div className={s.techMedia} data-tech-image><Image {...media.night} alt={media.night.alt} fill sizes="100vw" placeholder="blur"/></div><div><span className={s.eyebrow}>CONSTRAINTS, MADE COMPUTABLE</span><h2>The engine<br/>behind the plan.</h2><Link className={s.button} href="/docs#optimizer">Explore the model ↗</Link></div><div className={s.techSpecs}>CP-SAT constraint solver<br/>Selected FAR Part 117 checks<br/>Deterministic replay mode</div></section>}
function Stats(){
 const ref=useRef<HTMLElement>(null),stats=[{value:facts.disruptionTypes,label:"Disruption types in the event catalog",href:"/faq#disruption-types"},{value:facts.recoveryObjectives,label:"Recovery objectives to compare",href:"/docs#optimizer"},{value:facts.replayWorkers,label:"Seeded solver worker in replay mode",href:"/faq#determinism"}]
 useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add("(min-width:768px) and (prefers-reduced-motion:no-preference)",()=>{gsap.to(ref.current!.querySelector("[data-stats-heading]"),{scrollTrigger:{trigger:ref.current,start:"top 110px",end:"bottom bottom",pin:ref.current!.querySelector("[data-stats-heading]"),pinSpacing:false}})},ref);mm.add("(prefers-reduced-motion:no-preference)",()=>{ref.current!.querySelectorAll<HTMLElement>("[data-stat]").forEach(row=>{const number=row.querySelector<HTMLElement>("strong")!,count={value:0},end=Number(number.dataset.value);gsap.to(count,{value:end,snap:{value:1},ease:"none",onUpdate:()=>{number.textContent=String(count.value)},scrollTrigger:{trigger:row,start:"top 88%",end:"center 55%",scrub:.6}});gsap.from(row.querySelector("i"),{scaleX:0,scrollTrigger:{trigger:row,start:"top 90%",end:"top 50%",scrub:true}})})},ref);return()=>mm.revert()},[])
 return <section ref={ref} id="benchmarks" className={`${s.section} ${s.stats}`}><div className={s.statsHeading} data-stats-heading><div className={s.statsThumb}><Image {...media.sunset} alt={media.sunset.alt} fill sizes="190px" placeholder="blur"/></div><h2><span className={s.muted}>WE MODEL<br/>DISRUPTION.</span><br/>WE RETURN<br/>THE PLAN.</h2></div><div className={s.statColumn}><p>A recovery decision should come with its workings. Explore the model, compare the trade-offs, and replay the scenario that produced the result.</p><span className={s.eyebrow}>ENGINEERING YOU CAN INSPECT</span>{stats.map(stat=><div className={s.stat} key={stat.label} data-stat><i/><strong data-value={stat.value} aria-hidden="true">{stat.value}</strong><span className="sr-only">{stat.value}</span><p>{stat.label}</p><Link href={stat.href as Route}>See how this is defined ↗</Link></div>)}</div></section>
}
function Runway(){const ref=useRef<HTMLElement>(null);useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add("(prefers-reduced-motion:no-preference)",()=>{const root=ref.current!,plane=root.querySelector("[data-runway-plane]")!,clock=root.querySelector("[data-clock]")!,state={p:0};gsap.to(state,{p:1,ease:"none",onUpdate:()=>{const minutes=Math.round(state.p*1439);clock.textContent=`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}Z`;gsap.set(plane,{y:state.p*(root.querySelector<HTMLElement>("[data-strip]")!.clientHeight-320)})},scrollTrigger:{trigger:root,start:"top 50%",end:"bottom 80%",scrub:.6}});root.querySelectorAll("[data-constraint]").forEach(block=>gsap.from(block,{opacity:.25,y:24,scrollTrigger:{trigger:block,start:"top 85%",end:"top 50%",scrub:.4}}))},ref);return()=>mm.revert()},[]);return <section ref={ref} id="constraints" className={s.runway}><div className={s.runwayIntro}><div className={s.clock}><span data-clock aria-hidden>00:00Z</span><span>SIMULATED OPERATING DAY</span></div><h2><span className={s.muted}>RECOVERY</span><br/>AT EVERY<br/>CONSTRAINT.</h2><p>The plan has to survive the next departure, the next assignment, and the next shift.</p></div><div className={s.strip} data-strip aria-hidden><div className={s.runwayPlane} data-runway-plane><Image src="/images/olus/aircraft-top.png" alt="" fill sizes="230px"/></div></div><div className={s.constraints}>{constraints.map(([title,copy])=><article className={s.constraint} key={title} data-constraint><span className={s.dotIcon} aria-hidden/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>}
function ValidationFlyover(){
 const ref=useRef<HTMLElement>(null)
 useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add("(prefers-reduced-motion:no-preference)",()=>{
  const root=ref.current!,plane=root.querySelector<HTMLElement>("[data-fly-plane]")!,shadow=root.querySelector<HTMLElement>("[data-fly-shadow]")!,blur=root.querySelector<HTMLElement>("[data-fly-blur]")!
  const path=()=>[{x:-plane.offsetWidth,y:root.offsetHeight*.5},{x:(root.offsetWidth-plane.offsetWidth)/2,y:root.offsetHeight*.3},{x:root.offsetWidth,y:root.offsetHeight*.1}]
  gsap.set([plane,shadow,blur],{top:0,xPercent:0,yPercent:0,rotation:0})
  const aircraft=gsap.to([plane,blur],{paused:true,duration:1,ease:"none",motionPath:{path:path(),autoRotate:true}})
  const shade=gsap.to(shadow,{paused:true,duration:1,ease:"none",opacity:.22,motionPath:{path:path().map(point=>({x:point.x+24,y:point.y+32})),autoRotate:true}})
  const progress=gsap.utils.clamp(0,1),state={p:0}
  gsap.to(state,{p:1,ease:"none",onUpdate:()=>{aircraft.progress(progress(gsap.utils.mapRange(0,1,0,1,state.p)));shade.progress(progress(state.p-.04))},scrollTrigger:{id:"olus-flyover",trigger:root,start:"top bottom",end:"bottom top",scrub:.6,onRefresh:()=>{aircraft.vars.motionPath={path:path(),autoRotate:true};shade.vars.motionPath={path:path().map(point=>({x:point.x+24,y:point.y+32})),autoRotate:true};aircraft.invalidate();shade.invalidate()}}})
  gsap.fromTo(root.querySelector("h2"),{backgroundPosition:"100% 0"},{backgroundPosition:"0% 0",ease:"none",scrollTrigger:{trigger:root,start:"top bottom",end:"center 35%",scrub:.6}})
 },ref);return()=>mm.revert()},[]);
 return <section ref={ref} id="decisions" className={s.validation}><div className={s.validationInner}><span className={s.eyebrow}>DESIGNED AROUND THE DISPATCHER</span><h2>CLARITY,<br/>WHEN THE<br/>PRESSURE IS ON.</h2><blockquote className={s.quote}><cite><span className={s.quoteIndex}>01</span>Duty manager<br/>Illustrative perspective</cite><p>“Show me which flight moved, which constraint forced it, and what happens to the next rotation.”</p></blockquote><blockquote className={s.quote}><cite><span className={s.quoteIndex}>02</span>Operations researcher<br/>Illustrative perspective</cite><p>“Let me replay the inputs and inspect the trade-off. A recommendation needs an explanation.”</p></blockquote><p className={s.small}>Illustrative product perspectives, not customer testimonials or airline endorsements.</p></div><div className={s.flyShadow} data-fly-shadow aria-hidden><Image src="/images/olus/aircraft-top.png" alt="" fill sizes="110vw"/></div><div className={s.flyBlur} data-fly-blur aria-hidden/><div className={s.flyPlane} data-fly-plane aria-hidden><Image src="/images/olus/aircraft-top.png" alt="" fill sizes="110vw"/></div></section>}
function BuildLog(){const entries=[{type:"SOLVER / MODEL NOTES",title:"A feasible plan is a starting point. Know when it is optimal.",image:media.approach,href:"/faq#cp-sat"},{type:"CREW / CONSTRAINTS",title:"What the Part 117 model checks, and where its scope ends.",image:media.night,href:"/faq#part-117"},{type:"ENGINEERING / REPLAY",title:"Frozen inputs. Seeded search. A decision you can revisit.",image:media.hero,href:"/faq#determinism"}];return <section id="build-log" className={s.section}><header className={s.newsHeader}><h2>Inside the engine.</h2><Link className={s.outlineButton} href="/docs">Read the documentation ↗</Link></header><div className={s.newsGrid}>{entries.map(entry=><Link key={entry.type} href={entry.href as Route} className={s.newsCard}><span className={s.eyebrow}>{entry.type}</span><h3><span>{entry.title}</span></h3><div className={s.newsImage}><Image {...entry.image} alt={entry.image.alt} fill sizes="(max-width:767px) 90vw, 33vw" placeholder="blur"/></div></Link>)}</div></section>}
function SkyInterlude(){const ref=useRef<HTMLElement>(null);useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add("(prefers-reduced-motion:no-preference)",()=>{const root=ref.current!;root.querySelectorAll("[data-cloud]").forEach((cloud,i)=>gsap.fromTo(cloud,{y:80},{y:-180*(i+1),ease:"none",scrollTrigger:{trigger:root,start:"top bottom",end:"bottom top",scrub:true}}));gsap.fromTo(root.querySelector("[data-sky-plane]"),{x:-200,y:80,rotation:-15},{x:()=>innerWidth+200,y:-100,rotation:-6,ease:"none",scrollTrigger:{trigger:root,start:"top bottom",end:"bottom top",scrub:1}});root.querySelectorAll("[data-beat]").forEach(line=>gsap.fromTo(line,{y:24,opacity:0},{y:0,opacity:1,ease:"none",scrollTrigger:{trigger:line,start:"top 95%",end:"top 65%",scrub:.6}}));gsap.fromTo(root.querySelector("h2"),{opacity:1,y:0},{opacity:0,y:-40,ease:"none",scrollTrigger:{trigger:root,start:"top top",end:"top -45%",scrub:.6}})},ref);return()=>mm.revert()},[]);return <section ref={ref} className={s.sky} aria-labelledby="sky-title"><h2 id="sky-title">Wind,<br/>bound.</h2>{[0,1].map(i=><svg key={i} className={`${s.cloud} ${i?s.cloudBack:""}`} data-cloud viewBox="0 0 1000 600" aria-hidden><path fill="currentColor" d="M0 600V400Q-50 260 130 290Q70 70 270 120Q350-70 490 100Q700 30 710 260Q880 110 900 330Q1100 280 1000 600Z"/></svg>)}<div className={s.skyPlane} data-sky-plane aria-hidden><Image src="/images/olus/aircraft-top.png" alt="" fill sizes="200px"/></div><div className={s.skyBeats}><span className={s.eyebrow}>OLUS / CHAOS INTO CONTROL</span><p data-beat>The weather will change.</p><p data-beat>The constraints make the next move clear.</p><p data-beat>Give the day a way forward.</p></div></section>}
export function RecoveryStory(){
 const ref=useRef<HTMLDivElement>(null)
 useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add("(prefers-reduced-motion:no-preference)",()=>{
  ref.current!.querySelectorAll<HTMLElement>("p").forEach(paragraph=>{
   if((paragraph.textContent?.length??0)<90 || paragraph.closest("footer"))return
   const color=getComputedStyle(paragraph).color
   gsap.fromTo(paragraph,{backgroundImage:`linear-gradient(90deg,${color} 44%,var(--bone-200) 56%)`,backgroundSize:"230% 100%",backgroundPosition:"100% 0",backgroundClip:"text",color:"transparent"},{backgroundPosition:"0% 0",ease:"none",scrollTrigger:{trigger:paragraph,start:"top 90%",end:"bottom 35%",scrub:.6}})
  })
 },ref);return()=>mm.revert()},[])
 return <div ref={ref} className={s.story}><noscript><style>{`.${s.galleryPin}{height:auto;min-height:0;padding:64px 24px}.${s.galleryTrack}{position:static;display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:24px;padding:24px 0}.${s.galleryCard}{width:100%;transform:none}.${s.galleryFoot}{position:static}.${s.validation} h2{background:none;color:var(--text-inv)!important}`}</style></noscript><Gallery/><RecoveryJourney/><Technology/><Stats/><Runway/><ValidationFlyover/><NetworkGlobe/><BuildLog/><SkyInterlude/><RecoveryFooter/></div>}

