"use client"
import {useMemo,useRef,useState} from "react"
import {useQuery} from "@tanstack/react-query"
import {apiClient} from "@/lib/api"
import {useSimulationStore,type ScheduledFlight} from "@/stores/simulation"
import {useWorkspaceData} from "./workspace-data"
import s from "./plan-workbench.module.css"
type Explanation={rationale:string;counterfactuals:{flight_id:string;summary:string;delta_cost_usd:number;delta_pax_delay_min:number;delta_co2_kg:number}[]}
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n)
export function PlanWorkbench(){
 const {runId}=useWorkspaceData()
 const {schedule,recoveryPlans,flightStates}=useSimulationStore()
 const [requested,setPlanId]=useState("A"),[tab,setTab]=useState("timeline"),[zoom,setZoom]=useState(1),[selected,setSelected]=useState<string|null>(null),[cursor,setCursor]=useState<number|null>(null)
 const before=useRef<HTMLDivElement>(null),after=useRef<HTMLDivElement>(null)
 const plan=recoveryPlans.find(p=>p.plan_id===requested)||recoveryPlans[0],planId=plan?.plan_id||requested
 const explanation=useQuery({queryKey:["plan-explanation",runId,plan],enabled:tab==="explain"&&!!plan,queryFn:async()=>{const {data}=await apiClient.post<Explanation>(runId?`/runs/${encodeURIComponent(runId)}/explain`:"/recovery/explain",{plan_id:planId,top_n:12});return data},retry:false})
 const rows=useMemo(()=>{
  const tails=new Map<string,{tail:string;flights:ScheduledFlight[];recovered:ScheduledFlight[]}>()
  const row=(tail:string)=>{let r=tails.get(tail);if(!r){r={tail,flights:[],recovered:[]};tails.set(tail,r)}return r}
  const swaps=new Map(plan?.aircraft_swaps.map(f=>[f.flight_id,f.new_aircraft])||[])
  for(const f of schedule){if(!Number.isFinite(Date.parse(f.scheduled_departure))||!Number.isFinite(Date.parse(f.scheduled_arrival)))continue;const tail=f.tail_number||f.aircraft_id||"Unassigned";row(tail).flights.push(f);row(swaps.get(f.id)||tail).recovered.push(f)}
  return [...tails.values()].sort((a,b)=>a.tail.localeCompare(b.tail)).map(r=>({...r,flights:r.flights.sort((a,b)=>Date.parse(a.scheduled_departure)-Date.parse(b.scheduled_departure)),recovered:r.recovered.sort((a,b)=>Date.parse(a.scheduled_departure)-Date.parse(b.scheduled_departure))}))
 },[schedule,plan])
 const start=Math.min(...schedule.map(f=>Date.parse(f.scheduled_departure)).filter(Number.isFinite)),end=Math.max(...schedule.map(f=>Date.parse(f.scheduled_arrival)).filter(Number.isFinite)),span=Math.max(3600000,end-start+Math.max(0,...(plan?.delayed_flights.map(f=>f.delay_minutes)||[]))*60000)
 const flight=schedule.find(f=>f.id===selected),change=plan?.delayed_flights.find(f=>f.flight_id===selected),swap=plan?.aircraft_swaps.find(f=>f.flight_id===selected)
 function exportPlan(){if(!plan)return;const url=URL.createObjectURL(new Blob([JSON.stringify({plan,schedule,flight_states:flightStates},null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`olus-plan-${plan.plan_id}.json`;a.click();URL.revokeObjectURL(url)}
 function timeline(recovered:boolean){return <div className={s.scroll} ref={recovered?after:before} onScroll={e=>{const other=recovered?before.current:after.current;if(other){other.scrollLeft=e.currentTarget.scrollLeft;other.scrollTop=e.currentTarget.scrollTop}}} tabIndex={0} aria-label={recovered?"Recovery timeline, scroll to pan":"Baseline timeline, scroll to pan"}><div style={{minWidth:900*zoom}}><div className={s.axis}><strong>{recovered?`Plan ${planId}`:"Scheduled baseline"}</strong><div>{Array.from({length:7},(_,i)=><span key={i}>{new Date(start+span*i/6).toISOString().slice(11,16)}Z</span>)}</div></div>{rows.map(row=><div className={s.row} key={row.tail}><strong>{row.tail}</strong><div className={s.track} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setCursor(start+span*(e.clientX-r.left)/r.width)}}>{cursor!==null&&<i aria-hidden="true" className={s.cursor} style={{left:`${(cursor-start)/span*100}%`}}/>}{(recovered?row.recovered:row.flights).map(f=>{const delay=recovered?plan?.delayed_flights.find(d=>d.flight_id===f.id)?.delay_minutes||0:0,cancelled=recovered&&plan?.cancelled_flights.includes(f.id),reassigned=recovered&&plan?.aircraft_swaps.find(v=>v.flight_id===f.id);return <button key={f.id} className={s.block} data-cancelled={cancelled} data-recovered={recovered} aria-pressed={selected===f.id} onClick={()=>setSelected(f.id)} onKeyDown={e=>{if(["ArrowRight","ArrowLeft","Home","End"].includes(e.key)){e.preventDefault();const buttons=[...e.currentTarget.parentElement!.querySelectorAll("button")];const index=buttons.indexOf(e.currentTarget);buttons[e.key==="Home"?0:e.key==="End"?buttons.length-1:Math.max(0,Math.min(buttons.length-1,index+(e.key==="ArrowRight"?1:-1)))]?.focus()}}} style={{left:`${(Date.parse(f.scheduled_departure)+delay*60000-start)/span*100}%`,width:`${Math.max(1,(Date.parse(f.scheduled_arrival)-Date.parse(f.scheduled_departure))/span*100)}%`}} title={`${f.id}: ${f.origin} to ${f.destination}${cancelled?", cancelled":delay?`, delayed ${delay} minutes`:""}${reassigned?`, reassigned to ${reassigned.new_aircraft}`:""}`}>{cancelled?"× ":reassigned?"↗ ":""}{f.id}</button>})}</div></div>)}</div></div>}
 return <section className={s.workbench}><header><h2>Recovery workbench</h2><label>Plan <select value={planId} onChange={e=>setPlanId(e.target.value)}>{recoveryPlans.map(p=><option key={p.plan_id} value={p.plan_id}>{p.plan_id} · {p.objective_label}</option>)}</select></label><button disabled={!plan} onClick={exportPlan}>Export plan JSON</button></header><nav aria-label="Recovery workbench views">{["timeline","flights","explain","data"].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==="timeline"?"Plan & baseline":t==="explain"?"Why this plan":t==="flights"?"Flight list":"Source data"}</button>)}</nav>{!plan?<p role="status">Trigger a disruption to calculate recovery plans. The map and Events controls remain available behind this panel.</p>:<>
 {tab==="timeline"&&<><div className={s.controls}><label>Timeline zoom <input type="range" min={1} max={5} step={.5} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label>Time cursor <input type="range" min={0} max={1000} value={cursor===null?0:Math.round((cursor-start)/span*1000)} onChange={e=>setCursor(start+span*Number(e.target.value)/1000)}/></label><output>{cursor===null?"Point at timeline for UTC readout":new Date(cursor).toISOString().replace("T"," ").slice(0,19)+"Z"}</output></div><p>Pan either timeline to move both. Tab to a flight; use arrow keys within a tail. × Cancelled · ↗ Aircraft reassigned.</p>{rows.length?<figure className={s.pair}><figcaption>Scheduled and recovered flights by aircraft. Both timelines share the same UTC scale. Use Flight list for the table alternative.</figcaption>{timeline(false)}{timeline(true)}</figure>:<p>No valid schedule times are available.</p>}{flight&&<section className={s.detail} aria-label="Selected plan flight"><h3>{flight.id} · {flight.origin} → {flight.destination}</h3><dl><div><dt>Scheduled departure</dt><dd>{flight.scheduled_departure}</dd></div><div><dt>Recovery change</dt><dd>{plan.cancelled_flights.includes(flight.id)?"Cancelled":change?`Delayed ${change.delay_minutes} min`:"Unchanged"}</dd></div><div><dt>Aircraft</dt><dd>{swap?`${swap.old_aircraft} → ${swap.new_aircraft}`:flight.tail_number||flight.aircraft_id||"Unavailable"}</dd></div><div><dt>Reported cause</dt><dd>{flightStates[flight.id]?.reason||"No per-flight cause returned"}</dd></div></dl><p>Crew duty clocks and binding constraints are not included in this flight response.</p></section>}</>}
 {tab==="explain"&&<><p>{plan.summary||"Requesting the solver's explanation for this plan."}</p>{explanation.isPending&&<p role="status">Calculating counterfactuals...</p>}{explanation.isError&&<div role="alert">Could not load explanation. <button onClick={()=>void explanation.refetch()}>Retry explanation</button></div>}{explanation.data&&<><p>{explanation.data.rationale}</p><table><caption>Counterfactual decisions returned by the recovery service</caption><thead><tr><th scope="col">Flight / decision</th><th scope="col">Cost change</th><th scope="col">Passenger delay change</th><th scope="col">CO₂ change</th></tr></thead><tbody>{explanation.data.counterfactuals.map((c,i)=><tr key={`${c.flight_id}-${i}`}><th scope="row">{c.flight_id}<p>{c.summary}</p></th><td>{money(c.delta_cost_usd)}</td><td>{c.delta_pax_delay_min.toLocaleString()} passenger-min</td><td>{c.delta_co2_kg.toLocaleString()} kg</td></tr>)}</tbody></table>{!explanation.data.counterfactuals.length&&<p>No counterfactual decisions were returned.</p>}</>}<p>These are decision-flip comparisons. The service does not expose constraint shadow values.</p></>}
 {tab==="flights"&&<table><caption>Scheduled and recovered flights</caption><thead><tr><th scope="col">Flight</th><th scope="col">Route</th><th scope="col">Scheduled departure UTC</th><th scope="col">Plan delay</th><th scope="col">Aircraft assignment</th></tr></thead><tbody>{schedule.map(f=>{const delay=plan.delayed_flights.find(d=>d.flight_id===f.id),swap=plan.aircraft_swaps.find(v=>v.flight_id===f.id);return <tr key={f.id}><th scope="row">{f.id}</th><td>{f.origin} to {f.destination}</td><td>{f.scheduled_departure}</td><td>{plan.cancelled_flights.includes(f.id)?"Cancelled":`${delay?.delay_minutes||0} min`}</td><td>{swap?`${swap.old_aircraft} to ${swap.new_aircraft}`:f.tail_number||f.aircraft_id||"Unassigned"}</td></tr>})}</tbody></table>}
 {tab==="data"&&<details open><summary>Plan {planId} response</summary><pre>{JSON.stringify(plan,null,2)}</pre></details>}
 </>}</section>
}
